# (c) 2021, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

services:
  node-1:
    container_name: node-1
    image: avaplatform/avalanchego:latest
    command: [/files/start-node1.sh]
    ports:
        - '9661:9650'
        - '9671:9651'
    networks:
        - avalanche
    volumes:
        - ./files:/files
  node-2:
    container_name: node-2
    image: avaplatform/avalanchego:latest
    command: ["/files/start-node2.sh"]
    ports:
        - '9662:9650'
        - '9672:9651'
    networks:
        - avalanche
    volumes:
        - ./files:/files    
    depends_on: 
        - node-1
  node-3:
    container_name: node-3
    image: avaplatform/avalanchego:latest
    command: ["/files/start-node3.sh"]
    ports:
        - "9663:9650"
        - '9673:9651'
    networks:
        - avalanche
    volumes:
        - ./files:/files 
    depends_on: 
        - node-2
  node-4:
    container_name: node-4
    image: avaplatform/avalanchego:latest
    command: ["/files/start-node4.sh"]
    ports:
        - "9664:9650"
        - '9674:9651'
    networks:
        - avalanche
    volumes:
        - ./files:/files 
    depends_on: 
        - node-3  
  node-5:
    container_name: node-5
    image: avaplatform/avalanchego:latest
    command: ["/files/start-node5.sh"]
    ports:
        - "9665:9650"
        - '9675:9651'
    networks:
        - avalanche    
    volumes:
        - ./files:/files    
    depends_on: 
        - node-4   
             
version: '3'
volumes:
    files:
networks:
    avalanche:    